spring:
  application:
    name: Sushi Train Backend
  flyway:
    enabled: true
    locations: classpath:db/migration

#    jpa:
#      properties:
#        hibernate:
#          jdbc:
#            batch_size: 100
#          order_inserts: true
#          order_updates: true
#        open-in-view: false