spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sushitrain}
    username: ${DB_USER:sushitrain}
    password: ${DB_PASSWORD:sushitrain}
  jpa:
    hibernate:
      ddl-auto: validate